# -*- coding: utf-8 -*-
"""minimax.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qu7Ga0zaCFR2X58D7Jk34jZ3m0vr2B8f
"""

import math

def minimax(depth, node_index, is_max, scores, target_depth):
    # Base case: target depth reached (terminal leaf nodes)
    if depth == target_depth:
        return scores[node_index]

    if is_max:
        # Maximizing player: pick the highest value from children
        return max(minimax(depth + 1, node_index * 2, False, scores, target_depth),
                   minimax(depth + 1, node_index * 2 + 1, False, scores, target_depth))
    else:
        # Minimizing player: pick the lowest value from children
        return min(minimax(depth + 1, node_index * 2, True, scores, target_depth),
                   minimax(depth + 1, node_index * 2 + 1, True, scores, target_depth))

# Terminal leaf node values (the final outcomes of the game)
# Representing the bottom row of our tree: [3, 5, 2, 9]
leaf_scores = [3, 5, 2, 9]

# Calculate tree depth (for 4 leaves, depth is 2, since 2^2 = 4)
tree_depth = int(math.log2(len(leaf_scores)))

# Run the algorithm starting from the root (depth 0, index 0, Max's turn)
optimal_score = minimax(0, 0, True, leaf_scores, tree_depth)

print(f"The optimal value for the Max player is: {optimal_score}")