# -*- coding: utf-8 -*-
"""UCS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uli0dpdBJTDyox9A7Z4c3v0tUiiuP8y1
"""

import heapq

class Graph:
    def __init__(self):
        # Dictionary to store edges: { 'node': { 'neighbor': weight } }
        self.edges = {}

    def add_node(self, name):
        if name not in self.edges:
            self.edges[name] = {}

    def add_edge(self, u, v, weight):
        if u not in self.edges:
            self.edges[u] = {}
        if v not in self.edges:
            self.edges[v] = {}

        self.edges[u][v] = weight
        self.edges[v][u] = weight

    def uniform_cost_search(self, start, goal):
        # Priority queue stores tuples of (cost_so_far, node)
        open_set = []
        heapq.heappush(open_set, (0, start))

        # Keep track of the best previous node to reconstruct the path
        came_from = {}

        # Keep track of the exact minimum cost to reach each node
        g_score = {start: 0}

        # Keep track of fully explored nodes to avoid redundant work
        explored = set()

        while open_set:
            # Pop the node with the lowest cumulative cost
            current_cost, current = heapq.heappop(open_set)

            # Check if we've reached the goal
            if current == goal:
                path = []
                while current in came_from:
                    path.append(current)
                    current = came_from[current]
                path.append(start)
                path.reverse()
                return path, current_cost

            # If the node has already been explored with a cheaper or equal cost, skip it
            if current in explored:
                continue

            # Mark the current node as explored
            explored.add(current)

            # Evaluate all neighbors of the current node
            for neighbor, weight in self.edges.get(current, {}).items():
                tentative_g_score = current_cost + weight

                # If we found a cheaper path to the neighbor, update it
                if tentative_g_score < g_score.get(neighbor, float('inf')):
                    came_from[neighbor] = current
                    g_score[neighbor] = tentative_g_score
                    # Push the neighbor into the priority queue with its new cost
                    heapq.heappush(open_set, (tentative_g_score, neighbor))

        # If the queue is empty and goal hasn't been reached, return no path
        return None, float('inf')


if __name__ == "__main__":
    # Instantiate a new Graph object
    g = Graph()

    # Add nodes to the graph
    g.add_node('Start')
    g.add_node('A')
    g.add_node('B')
    g.add_node('C')
    g.add_node('Goal')

    # Add edges connecting the nodes along with their actual travel costs (weights)
    g.add_edge('Start', 'A', 1)
    g.add_edge('Start', 'B', 4)
    g.add_edge('A', 'B', 2)
    g.add_edge('A', 'C', 5)
    g.add_edge('B', 'C', 2)
    g.add_edge('C', 'Goal', 3)

    # Print out the edges and their weights to verify data
    print("Edges and Weights (Undirected):")
    printed_edges = set()
    for node, neighbors in g.edges.items():
        for neighbor, weight in neighbors.items():
            edge_tuple = tuple(sorted([node, neighbor]))
            if edge_tuple not in printed_edges:
                print(f"{node} <--> {neighbor} (Weight: {weight})")
                printed_edges.add(edge_tuple)

    # Execute the Uniform Cost Search from 'Start' to 'Goal'
    print("\nFinding path from 'Start' to 'Goal' using Uniform Cost Search...")
    path, cost = g.uniform_cost_search('Start', 'Goal')

    # Check if a valid path was returned and print the result
    if path:
        print(f"UCS Optimal Path: {' -> '.join(path)} (Total Cost: {cost})")
    else:
        print("No path found.")